version: "3.8"
services:
  better-banking-cache:
    container_name: better-banking-redis
    image: redis:latest
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
    restart: on-failure
  better-banking-db:
    container_name: better-banking-db
    image: 'mysql:8.0'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=better_banking
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: always
    volumes:
      - better-banking-db-datavolume:/var/lib/mysql
  better-banking:
    container_name: better-banking
    image: better-banking-pbikks:latest
    ports:
      - 9000:9000
    restart: on-failure
    depends_on:
      better-banking-db:
        condition: service_healthy
    links:
      - better-banking-db
      - better-banking-cache
    environment:
      - testnet.integration.client=better-banking
      - testnet.integration.secret=7yrbR8XpY45bcKPP
      - MYSQL_HOST=better-banking-db
      - io.betterbanking.integration.url-base=http://10.252.1.12:8080
volumes:
  better-banking-db-datavolume: